name: "common :: Checkout Java"
description: "common :: Checkout repository and setup JDK/Maven"

inputs:
  GITHUB_TOKEN:
    required: true
    description: "Just pass the secrets.GITHUB_TOKEN to this action as input."
  JDK_VERSION:
    required: true
    description: "The version of the JDK to setup."

runs:
  using: "composite"
  steps:
    - uses: ./aerius-github-actions/common/checkout
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    # Setup JDK / mvn, override by providing JDK_VERSION as input.
    - name: Set up JDK / mvn
      uses: actions/setup-java@v1
      with:
        java-version: ${{ inputs.JDK_VERSION }}

