name: "common :: Publish Maven Artifacts"
description: "common :: Publish Maven Artifacts - requires checkout-java to be run before"

inputs:
   NEXUS_USERNAME:
     required: true
     description: "The Nexus username needed to publish packages."
   NEXUS_PASSWORD:
     required: true
     description: "The Nexus password needed to publish packages."
   POM_PUBLISH_REPOSITORY_NAME:
     required: true
     description: "The repository as specified in the root POM to publish to."
   ROOT_POM_DIRECTORY:
     required: true
     description: "The directory where the root POM can be found."

runs:
  using: "composite"
  steps:
    - name: Publish Maven Artifacts
      uses: samuelmeuli/action-maven-publish@v1
      with:
        server_id: ${{ inputs.POM_PUBLISH_REPOSITORY_NAME }}
        nexus_username: ${{ inputs.NEXUS_USERNAME }}
        nexus_password: ${{ inputs.NEXUS_PASSWORD }}
        maven_args: -DskipTests -P publish -f ${{ inputs.ROOT_POM_DIRECTORY }}/pom.xml

