name: "pull_request event action"
description: "On pull_request event build AERIUS Java project, including running the unittests"

inputs:
   GITHUB_TOKEN:
     required: true
     description: "Just pass the secrets.GITHUB_TOKEN to this action as input."
   ROOT_POM_DIRECTORY:
     required: false
     description: "The directory where the root POM can be found."
     default: "."
   JDK_VERSION:
     required: false
     description: "The version of the JDK to setup."
     default: 11

runs:
  using: "composite"
  steps:
    - uses: ./../../common/checkout-java.yml
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        JDK_VERSION: ${{ inputs.JDK_VERSION }}

    - uses: ./../../common/cache-maven-packages.yml

    - uses: ./../../common/build-using-maven.yml
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        ROOT_POM_DIRECTORY: ${{ inputs.ROOT_POM_DIRECTORY }}

