name: "Build Docker images for a generic AERIUS project"
description: "Build Docker images for a AERIUS project"

inputs:
   GITHUB_TOKEN:
     required: true
     description: "Just pass the secrets.GITHUB_TOKEN to this action as input."
   DOCKER_IMAGE_NAME:
     required: true
     description: "The Docker image name to use when building."
   DOCKERFILE_DIRECTORY:
     required: false
     description: "The directory where the Dockerfile can be found."
     default: "repo"

runs:
  using: "composite"
  steps:
    - uses: ./aerius-github-actions/common/checkout
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}

    - name: Build Docker image
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: ${{ inputs.DOCKER_IMAGE_NAME }}
        workdir: ${{ inputs.DOCKERFILE_DIRECTORY }}/
        no_push: true

